assigness: []
harvest_options:
  goldcopy: false
  path: s3://ooi-data
  refresh: true
  test: false
instrument: RS03AXBS-LJ03A-05-HPIESA301
stream:
  method: streamed
  name: motor_current
workflow_config:
  schedule: 0 0 * * *
