name: All Stream Code Update

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.8
  CONDA_ENV: harvester

jobs:
  template-update:
    name: Template Update
    runs-on: ubuntu-20.04
    if: github.repository == 'ooi-data/stream_template'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if environment.yaml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yaml') }}
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ${{ env.CONDA_ENV }}
          environment-file: environment.yaml
          python-version: ${{ env.PYTHON_VERSION }}
          auto-activate-base: false
          use-only-tar-bz2: true
      - name: Print conda env
        run: |
          conda info
          conda list
      - name: Run code updates
        run: python .ci-helpers/code-updates.py
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
